version: "3.9"
services:
  webserver:
    container_name: webserver2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./apache_php_conf/php.ini:/usr/local/etc/php/php.ini
      - ./apache_log/:/var/log/apache2
    ports:
      - 80:80
      - 8090:8090
      #- 9003:9003
    depends_on:
      - mysql-db
      - redis
    networks:
      - local
    #extra_hosts:
      #- "host.docker.internal:host-gateway"

  mysql-db:
    container_name: mysql2
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ecommerce_sample
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      #- "3307:3306"
    volumes:
      - ./mysql_data/:/var/lib/mysql
    networks:
      - local
      
  phpmyadmin:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - local

  redis:
    build:
      dockerfile: ./redis/Dockerfile
    container_name: redis2
    environment:
      - REDIS_HOST=redis
    ports:
      - 6379:6379
    networks:
      - local
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - ./redis/redis.env

networks:
  local:
    driver: bridge